name: workflow_check_python_version
on:
  push:
    branches: [ "check_python_version" ]
  workflow_dispatch:
jobs: 
  build: 
    runs-on: ${{ matrix.os }}  
    strategy:  
      matrix:  
        python-version: ['3.11']  
        os: [windows-latest, ubuntu-latest]  
        
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: '3.11'
          cache: 'pip' 
          
      - name: Run a multi-line script
        run: |
          pip install --upgrade pip
          python -V
