# This is a basic workflow to help you get started with Actions

name: workflow_check_syntax

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "check_syntax" ]
  #pull_request:
  #  branches: [ "check_syntax" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3 
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: | 
          pip install --upgrade pip
          python -V 

      - name: Install flake8
        run: pip install --upgrade flake8
      - name: Check code style with flake8
        run: flake8
