# This is a basic workflow to help you get started with Actions 
name: workflow_main_check_syntax 

# Controls when the workflow will run 
on: 
  # Triggers the workflow on push or pull request events but only for the "main" branch 
  push: 
    branches: [ "main" ] 

  # Allows you to run this workflow manually from the Actions tab 

  workflow_dispatch: 


# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  syntax-check:
    runs-on: ${{ matrix.os }} 
  # This workflow contains a single job called "build" 

  build: 
    # The type of runner that the job will run on 
    runs-on: ubuntu-latest 
    strategy: 
      matrix: 
        python-version: [3.9, 3.10, 3.11]
        os: [windows-latest, ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job 
    steps: 
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v3  
        with:  
          python-version: ${{ matrix.python-version }} 
          cache: 'pip' # caching pip dependencies  

      # Runs a set of commands using the runners shell 
      - name: Run a multi-line script 
        run: |  
          sudo pip install --upgrade pip, 
          python -V.  

      - name: Install dependencies
        run: |
          sudo pip install --upgrade flake8, 
          sudo pip install --upgrade unittest.
          
      - name: Check code style with flake8
        run: flake8.

      - name: Run unittest
        run: python -m unittest discover
