name: workflow_main_check_syntax

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.9, 3.11]
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upgrade pip
        run: |
          sudo pip install --upgrade pip
          python -V

      - name: Install dependencies
        run: |
          sudo pip install --upgrade flake8
          sudo pip install --upgrade unittest

      - name: Check code style with flake8
        run: flake8 .

      - name: Run unittest
        run: python -m unittest discover
