name: workflow_main_check_syntax 
on: 
  push: 
    branches: [ "main" ] 
  workflow_dispatch: 
jobs:
  syntax-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
        os: [windows-latest, ubuntu-latest]

    steps: 
      - uses: actions/checkout@v3  
        with:  
          python-version: ${{ matrix.python-version }} 
          cache: 'pip' 

      - name: Run a multi-line script 
        run: |  
          pip install --upgrade pip
          python -V  

      - name: Install dependencies
        run: pip install --upgrade flake8
          
      - name: Check code style with flake8
        run: flake8

      - name: Run unittest
        run: python -m unittest discover
